#include<iostream>

using namespace std;
int main()
{
   // std::cout << "hello\n" ;
    int a ;
    cin >> a;

    cout<< "The value of a is: " << a << endl;

    char b = 5;
    cout << sizeof(b) << endl;

    char ch = 97;
    cout << ch << endl;

    int num = 'b';
    cout << num << endl;

    double d = 3.14;
    int x = (int)d +2 ;
    cout << "x =" << x << endl;

    // Explicit type conversion from double to int
   
}