#include <iostream>
using namespace std;

int main() {
   /* int bronum;

    cout << "Enter no of bros: " << endl;
    cin >> bronum;
    if (bronum > 0) {
        cout << "You have " << bronum << " brothers." << endl;
    } else if (bronum == 0) {
          cout << "You have no brothers." << endl;
    } else {
        cout << "Invalid input. Number of brothers cannot be negative." << endl;
    } */

    // practice problem
    int n;
    if(cin >> n) {
        cout << "string" << endl;
    }
}